version: "3.7"

services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - x-net

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 50000:50000
    environment:
      - NODE_ENV=development
      - PORT=50000
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - x-net
    depends_on:
      - db

networks:
  x-net:

volumes:
  db:
